ALTER TABLE `profile`
	DROP COLUMN `access_token`,
	DROP COLUMN `access_token_datetime`;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `profile_key`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;